### ISSUE TITLE
I can't find this pkg from npm.

### ISSUE THREAD

**Issue by Zen33** [gwinnem/vue-responsive-grid-layout#1]
thanks for this good components, how can I install this package from npm?

**Comment by gwinnem** [comment]
Hello Zen,
I still have some work todo before it is ready for the first version.
Check again in 2 weeks and it should be released by then.

Regards

Geirr Winnem

**Comment by Zen33** [comment]
That's great, I look forward to get the release version:)

**Comment by gwinnem** [comment]
Hi, the package is now published to npm:
https://www.npmjs.com/package/vue-ts-responsive-grid-layout?activeTab=readme

**Comment by Zen33** [comment]
Great:)
