### ISSUE TITLE
weird convulsion

### ISSUE THREAD

**Issue by liesauer** [gwinnem/vue-responsive-grid-layout#10]
https://vue-ts-responsive-grid-layout.winnem.tech/examples/11-example

![GIF 2023-6-24 11-25-01](https://github.com/gwinnem/vue-responsive-grid-layout/assets/8676741/96d2af64-35f1-4ddd-b022-3773d35ff9c4)

**Comment by gwinnem** [comment]
@liesauer 
First tnxs for finding this bug.
It looks like i need to do some heavy refactoring to fix this.
It will take some time but i will start doing asap

**Comment by liesauer** [comment]
just take your time

**Comment by gwinnem** [comment]
I am planning to move the drag & drop functionality inside the component
instead of having it external. And if needed I will throttle the changes
that are being done in the ui.

**Comment by gwinnem** [comment]
Fix is coming up in version 1.2.3 planned to be released end og october 2023.
