### ISSUE TITLE
No type declaration file

### ISSUE THREAD

**Issue by kingyue737** [gwinnem/vue-responsive-grid-layout#11]
# Expected Behavior

The package can be imported without TypeScript error

# Current Behavior

No declaration file
![image](https://github.com/gwinnem/vue-responsive-grid-layout/assets/40021217/36edb8a7-1752-40fc-b530-ace3edb7141e)

# Failure Information (for bugs)

Could not find a declaration file for module 'vue-ts-responsive-grid-layout'. test/node_modules/.pnpm/vue-ts-responsive-grid-layout@1.2.1_@interactjs+core@1.10.18_@interactjs+utils@1.10.18_vue@3.3.4/node_modules/vue-ts-responsive-grid-layout/dist/vue-ts-responsive-grid-layout.umd.js implicitly has an `any` type.

`typings` in `package.json` should be `./dist/types/components/index.d.ts`
And I don't understand why you set both `typings` and `types` (but with different values) in `package.json`

**Comment by kingyue737** [comment]
I found even patching `typings` is not usable because the declaration files in this package are containing many `@` in path which may break the types of the whole project.

![image](https://github.com/gwinnem/vue-responsive-grid-layout/assets/40021217/c0f1ff97-d4bb-46f1-a306-b4603e0e869e)

**Comment by gwinnem** [comment]
Pls check this [Issue: 3](https://github.com/gwinnem/vue-responsive-grid-layout/issues/3).
Let me know if this solved your issue.
Regards

Geirr

**Comment by kingyue737** [comment]
No, a TypeScript project should provide correct types to give type check and auto-completion in SFC template, not an empty shim file mentioned in #3.

For example, when I type drag, IDE will auto-complete the props if a correct type declaration file of this component is detected：
![image](https://github.com/gwinnem/vue-responsive-grid-layout/assets/40021217/c8cdab5e-67ea-4eb0-a9e2-c0c3e69eb9d6)

**Comment by kingyue737** [comment]
Switched to https://github.com/qmhc/grid-layout-plus which is a perfect TypeScript rewrite of vue-grid-layout to vue 3. Thanks for your work in this project. Closing
