### ISSUE TITLE
dynamic change columns, item will overlap

### ISSUE THREAD

**Issue by UTing1119** [gwinnem/vue-responsive-grid-layout#12]
# Expected Behavior

dynamic change columns and it should calculate new item's position correctly.

# Current Behavior

item will overlap

## Steps to Reproduce

1. dynamic change columns
2. the item which is overflow will change to position 1 and overlap the first item

![wcvb9-ws07f](https://github.com/gwinnem/vue-responsive-grid-layout/assets/74576629/b1388ff2-55c3-424e-970b-71ce02b715f6)

I will try to fix it, plz let me know if the overflow item is static, how would you want it to behave

**Comment by gwinnem** [comment]
Hi there,
I think this is a side effect after we fixed your previous bug.

Rgds

Geirr

**Comment by gwinnem** [comment]
Hi, did you manage to make a fix for this ?

**Comment by UTing1119** [comment]
yes, I was tryna find the reason why the resize event will be triggered when col number is set by user.

do you have any plans to refactor?

**Comment by gwinnem** [comment]
Hi @UTing1119 
I am doing some work on the component right now, and will look into this issue to. Just wanted to check up on your progress on this issue.

**Comment by gwinnem** [comment]
@UTing1119 may I ask what you are using the component for ?

Regards

Geirr

**Comment by UTing1119** [comment]
@gwinnem if you're referring to dragging items, that's because I'm tryna set up a template item that will be added to the GridLayout correctly.
and maybe provide slots for users to customize its appearance.

but unfortunately I have no time to fix it or refactor it.
if any idea, plz let me know

**Comment by UTing1119** [comment]
still not work in version 1.2.2/1.2.4/1.2.5

**Comment by gwinnem** [comment]
@UTing1119 
I'll try to fix this asap.
Currently working on the [Resize enhancement issue](https://github.com/gwinnem/vue-responsive-grid-layout/issues/27)
But will pause this and start working on this issue.

**Comment by gwinnem** [comment]
Hi @UTing1119 
If im correct, it  is alway the top left GridItem which have this issue ?

**Comment by UTing1119** [comment]
I think it's more like the item overflows right side of the layout.

I guess it's because in ```src/core/helpers/responsiveUtils.ts```, both `moveToCorrectPlace` and `correctBounds` function only consider about whether to collide with static items or not.

**Comment by gwinnem** [comment]
> I think it's more like the item overflows right side of the layout.
> 
> I guess it's because in `src/core/helpers/responsiveUtils.ts`, both `moveToCorrectPlace` and `correctBounds` function only consider about whether to collide with static items or not.

It is strange the behavior, but with multiple statics the result is a lot of overflows when dynamically changes the max col value.

I am looking into it now and will release a new version asap.

**Comment by gwinnem** [comment]
Should be fixed in 1.2.9
