### ISSUE TITLE
Layout update event is raised before update is finished

### ISSUE THREAD

**Issue by SamGeens** [gwinnem/vue-responsive-grid-layout#19]
# Expected Behavior

Layout update event is raised when updating the layout finishes. Like said in the docs: 

> Every time the layout has finished updating and positions of all grid-items are recalculated

# Current Behavior

The layout event is raised multiple times before updating the layout is finished

# Failure Information (for bugs)

https://github.com/gwinnem/vue-responsive-grid-layout/assets/56310463/22316568-1556-41ff-93ee-686e743618f7

## Steps to Reproduce

The behavior can be seen in [this](https://codesandbox.io/p/sandbox/vue-ts-responsive-grid-layout-nuxt3-sknfv8?file=%2Fpages%2Flayoutupdateevent.vue%3A178%2C14) codesandbox.

**Comment by gwinnem** [comment]
Hi @SamGeens , tnxs for the feedback. Im on a 3 week holiday right now but I will start looking into the issues you have reported the 3rd week of october

**Comment by SamGeens** [comment]
Enjoy your holiday! I’m looking very much forward to version 1.2.3. In the meantime I’ll explore this library a bit further to and post my questions.

**Comment by gwinnem** [comment]
Im happy for your feedback, keep up the good work.

**Comment by gwinnem** [comment]
Hi Sam, this event is ment to fire every time the layout is recalculated.
I will introduce a new event which fires only when the final layout update is completed.
The above event will fire when a item is being dragged, dropped or resized.

**Comment by SamGeens** [comment]
I see, thanks!
