### ISSUE TITLE
Close button css is different than in the example

### ISSUE THREAD

**Issue by SamGeens** [gwinnem/vue-responsive-grid-layout#20]
# Expected Behavior

Have a nice close button like in the example docs.

![image](https://github.com/gwinnem/vue-responsive-grid-layout/assets/56310463/687a2672-c027-45fb-87e3-1bb9d5aa35e1)

# Current Behavior

When I use the exact same code the close button doesn't look the same and the text 'close' is displayed.
![image](https://github.com/gwinnem/vue-responsive-grid-layout/assets/56310463/abcdc2b4-d848-44e5-b214-42c284ec4b6f)

## Steps to Reproduce

The behavior can be seen in [this](https://codesandbox.io/p/sandbox/vue-ts-responsive-grid-layout-nuxt3-sknfv8?file=%2Fpages%2Fexample10.vue%3A255%2C48) codesandbox.

**Comment by gwinnem** [comment]
Removed the span which was displaying the Close text.
Update will come in v1.2.3

**Comment by SamGeens** [comment]
Hi, I updated the plugin to version 1.2.4 but for some reason the close text is still being displayed.

## Steps to Reproduce

The behavior can be seen in [this](https://codesandbox.io/p/sandbox/vue-ts-responsive-grid-layout-nuxt3-sknfv8?file=%2Fpages%2Fexample10.vue%3A255%2C48) codesandbox.
