### ISSUE TITLE
GridItem heigth not calculated correct when resizing a GridItem

### ISSUE THREAD

**Issue by gwinnem** [gwinnem/vue-responsive-grid-layout#30]
# Expected Behavior
I expect the item height to be the actual calcalution the documentation describes: The value is a number that is multiplied by rowHeight.

Please describe the behavior you are expecting
When the rowHeight is set to 30px, I expect that the calculation of the rowHeight to be calculate correct. So when the rowHeight is set to 30px and you resize a GridItem to double the size should be 60px.

# Current Behavior
Currently the calculation is off. When you double the height it is calculated to: 70px.

# Failure Information (for bugs)
It looks like the height calculation is also taking the gap values into account.

**Comment by UTing1119** [comment]
but if the height remains 60px, it would not be able to align to the second line.
it will miss the height of gap value.

simple example:
![image](https://github.com/gwinnem/vue-responsive-grid-layout/assets/74576629/2bd92855-553e-483c-a400-3e1ef7075391)

is there any other way to avoid the align question?

**Comment by gwinnem** [comment]
> but if the height remains 60px, it would not be able to align to the second line. it will miss the height of gap value.
> 
> simple example: ![image](https://user-images.githubusercontent.com/74576629/278967581-2bd92855-553e-483c-a400-3e1ef7075391.png)
> 
> is there any other way to avoid the align question?

You are correct @UTing1119 .
I will keep this open while i do some checks about the calculation for grid items having h > 1.

**Comment by gwinnem** [comment]
Closing this based on the feedback from @UTing1119 above.
