### ISSUE TITLE
if item is static (won't be draggable, resizable or moved by other items). but setting isStacic will be moved by other items.

### ISSUE THREAD

**Issue by Hbllol** [gwinnem/vue-responsive-grid-layout#38]
# Expected Behavior

setting isStatic is affected

# Current Behavior

setting isStatic is not affected

**Comment by gwinnem** [comment]
Hi @Hbllol 
Can you please create a example where I can see the issue better ?

Regards

Geirr

**Comment by gwinnem** [comment]
Not able to reproduce
