### ISSUE TITLE
Incorrect GridItem display on different screen resolutions

### ISSUE THREAD

**Issue by polom01** [gwinnem/vue-responsive-grid-layout#4]
# Expected Behavior

The GridItem should be displayed appropriately on the page depending on the screen resolution

# Current Behavior

The GridItem is displayed the same on every screen size
![image](https://user-images.githubusercontent.com/40596276/231963555-73294e7b-bcc8-4175-b4dc-059be34b6f3e.png)
![image](https://user-images.githubusercontent.com/40596276/231963702-85ca85dc-569a-4a3f-95ae-ab192924c211.png)

## Steps to Reproduce

https://codesandbox.io/s/bitter-dew-oxfdwt?file=/app.vue

## Context

* Nuxt 3 (version 3.3.1)
* vue-ts-responsive-grid-layout (1.2.0 version)

**Comment by gwinnem** [comment]
Strange, can you send me the row height you are using.
When im trying to recreate this it behaves correctly for me.
![image](https://user-images.githubusercontent.com/6427120/232012511-fe232f1d-5468-478b-9768-0e75f5edd092.png)

![image](https://user-images.githubusercontent.com/6427120/232012688-e6fb54d2-3a6d-4a17-9e97-534668187ac3.png)

**Comment by gwinnem** [comment]
Set the responsive prop on the GridLayout to true. This should fix the issue.

**Comment by polom01** [comment]
After updating to 1.2.0  start working :) 
Thx for help
