### ISSUE TITLE
option "responsive" not working

### ISSUE THREAD

**Issue by KsslJan** [gwinnem/vue-responsive-grid-layout#51]
# Expected Behavior

When resizing the window, the items should reorder and be displayed.

# Current Behavior

The items overlap as soon as the window width is decreased.

## Steps to Reproduce

1. Open example 7 ("responsive breakpoints") on the documentation website.
2. Decrease the window width.

### Release version: 1.2.6

https://github.com/gwinnem/vue-responsive-grid-layout/assets/88673756/0299a52c-d5d9-47fa-8afe-465ac775f1af

**FYI** I have tried to get it to work locally, without any luck yet.

**Comment by T0miii** [comment]
I wanted to check out the project to see what can be done regarding this responsive issue, but having problems installing the dependancy

![image](https://github.com/gwinnem/vue-responsive-grid-layout/assets/10532141/d58e5ca0-34b6-4533-b1f6-4665208bd304)

**Comment by T0miii** [comment]
The problem seems to be in the events:

```
export enum EGridLayoutEvent {
  BREAKPOINT_CHANGED = `breakpoint-changed`,
  CHANGED_DIRECTION = `changed-direction`,
  COLUMNS_CHANGED = `columns-changed`,
  CONTAINER_RESIZED = `container-resized`,
  DRAG_END = `dragend`,
  DRAG_MOVE= `dragmove`,
  DRAG_START = `dragstart`,
  LAYOUT_BEFORE_MOUNT = `layout-before-mount`,
  LAYOUT_CREATED = `layout-created`,
  LAYOUT_MOUNTED = `layout-mounted`,
  LAYOUT_READY = `layout-ready`,
  LAYOUT_UPDATED = `layout-updated`,
  LAYOUT_UPDATE = `layout-update`,
}
```

the layout-update event should be called something like `update:layout` as on the component v-model:layout is being referenced

**Comment by gwinnem** [comment]
Hi @T0miii 
Tnxs for the valuable feedback.
You have to create a pull request in order for me to be able to check the changes before it is being merged into the main branch

**Comment by T0miii** [comment]
I think i created one, should i do it differently?

https://github.com/gwinnem/vue-responsive-grid-layout/pull/53
