### ISSUE TITLE
Whether the types entry is an error

### ISSUE THREAD

**Issue by MrYua** [gwinnem/vue-responsive-grid-layout#9]
# Expected Behavior

Types can be exported as normal
![image](https://user-images.githubusercontent.com/124798344/235402585-c74eb70e-3802-46aa-861a-42a1eb9845e3.png)

# Current Behavior

Now I have to do this to get it
![image](https://user-images.githubusercontent.com/124798344/235402356-b4ee7f77-2939-489c-b84a-111fd543e32c.png)

**Comment by gwinnem** [comment]
@MrYua This is the expected behavior for now, will resort the issue with the build not creating the file index.d.ts and putting it into the npm package
